module "application_gateway" {
  source                         = "./modules/application-gateway"
  agwy_backend_pool_name         = local.application_gateway_settings.agwy_backend_pool_name
  agwy_name                      = local.application_gateway_settings.agwy_name
  agwy_public_ip_name            = local.application_gateway_settings.agwy_public_ip_name
  backend_http_settings_name     = local.application_gateway_settings.backend_http_settings_name
  frontend_ip_configuration_name = local.application_gateway_settings.frontend_ip_configuration_name
  frontend_https_port_name             = local.application_gateway_settings.frontend_port_name
  gateway_ip_configuration_name  = local.application_gateway_settings.gateway_ip_configuration_name
  http_listener_name             = local.application_gateway_settings.http_listener_name
  location                       = azurerm_resource_group.public.location
  request_routing_rule_name      = local.application_gateway_settings.request_routing_rule_name
  resource_group_name            = azurerm_resource_group.public.name
  snet_agwy_frontend_name        = local.network_settings.snet_agwy_frontend_name
  ssl_certificate_name           = var.ssl_certificate_name
  ssl_certificate_password       = var.ssl_certificate_password
  ssl_certificate_path           = var.ssl_certificate_path
  virtual_network_name           = module.network.vnet_name
  windows_servers                = module.windows_servers
}