---
- name: 'Copy nginx config and restart nginx'
  hosts: all
  become: yes
  
  vars:
    nginx_config: ../nginx/nginx.config.j2
    nginx_config_dest: /etc/nginx/conf.d/disketov.conf
  
  tasks:
    - name: 'Generate nginx config'
      template: src={{ nginx_config }} dest={{ nginx_config_dest }}

    - name: 'Restart nginx'
      service: "name=nginx state=restarted"