- hosts: all
  become: true
  tasks:
    - name: Download MS product repository
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb

    - name: Install MS product repository
      apt: deb=/tmp/packages-microsoft-prod.deb

    - name: Make sure HTTPS is supported by apt
      apt:
        name: apt-transport-https
        state: present
        update_cache: no

    - name: Install .NET Core SDK
      apt:
        name: dotnet-sdk-6.0
        state: present
        update_cache: yes