all:
  children:
    all_servers:
      children:
        db_servers:
          hosts:
            secondnode:
              ansible_host: 13.79.151.149
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
              ansible_user: razumovsky_r
              owner: Petya
        development:
          hosts:
            thirdnode:
              ansible_host: 13.79.150.253
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
              ansible_user: razumovsky_r
              owner: Sanya
        web_servers:
          hosts:
            firstnode:
              ansible_host: 13.69.137.115
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
              ansible_user: razumovsky_r
              owner: Vasya
    ungrouped: { }
