#file: noinspection YAMLSchemaValidation
all:
  children:
    all_servers:
      children:
        app_servers:
          hosts:
            app_server:
              ansible_host: ansibleappserver.devtest.team
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
              ansible_user: razumovsky_r
              owner: Sanya
              htmlFile: blue.html
              port: 8090
        db_servers:
          hosts:
            db_server:
              ansible_host: ansibledbserver.devtest.team
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
              ansible_user: razumovsky_r
              owner: Petya
              htmlFile: green.html
              port: 8090
        web_servers:
          hosts:
            web_server:
              ansible_host: ansiblewebserver.devtest.team
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
              ansible_user: razumovsky_r
              owner: Vasya
              htmlFile: red.html
              port: 8090
    ungrouped: {}
