name: Ansible test

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

env:
  VM_IP_ADDRESS: 13.69.137.115
  SSH_USER: razumovsky_r

jobs:
  ansible-test:
    name: Ansible test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Configure SSH'
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >>~/.ssh/config <<END
          Host staging
            HostName ${{ env.VM_IP_ADDRESS }}
            User ${{ env.SSH_USER }}
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.UBUNTU_SSH_KEY }}

      - name: 'Print SSH Config'
        run: cat ~/.ssh/config
        shell: bash

      - name: Test SSH Config
        run: ssh staging -v "hostname"
        shell: bash

      - name: 'Test SSH Connection'
        run: ssh -v ${{ env.SSH_USER }}@${{ env.VM_IP_ADDRESS }} "hostname"
        shell: bash

      - name: Check ansible version
        run: ansible --version
        shell: bash
        
      - name: Run ansible playbook
        working-directory: './playbooks'
        run: ansible-playbook -i inventory_with_groups_and_aliases.ini ping.yml
        shell: bash