trigger: none

pr: none

variables:
  - name: 'vmIpAddress'
    value: '13.69.137.115'
  - name: 'sshUser'
    value: 'razumovsky_r'

stages:
  - stage: 'Ansible_Test'
    displayName: 'Ansible Test'
    jobs:
      - job: 'Ansible_Test'
        displayName: 'Ansible Test'
        pool:
          vmImage: 'ubuntu-latest'
        
        steps:
          - task: DownloadSecureFile@1
            name: sshKey
            displayName: 'Download SSH key'
            inputs:
              secureFile: 'id_rsa'

          - script: |
              echo "Installing $(sshKey.secureFilePath) to SSH config"
              mkdir -p ~/.ssh/
              cp $(sshKey.secureFilePath) ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
              cat >>~/.ssh/config <<END
              Host staging
                HostName $(vmIpAddress)
                User $(sshUser)
                IdentityFile ~/.ssh/id_rsa
                StrictHostKeyChecking no
              END
            displayName: 'Add SSH Config'

          - script: cat ~/.ssh/config
            displayName: 'Print SSH Config'

          - script: ssh staging -v "hostname"
            displayName: 'Test SSH Config'

          - script: ssh -v $(sshUser)@$(vmIpAddress) "hostname"
            displayName: 'Test SSH Connection'

          - script: ansible --version
            displayName: 'Check ansible version'

          - script: ansible-playbook -i inventory_with_groups_and_aliases.ini ping.yml
            displayName: 'Run ansible playbook'
            workingDirectory: './playbooks'